volumes:
  certs:
    external: true
    name: reverse-proxy_certs
  config:
    external: true
    name: drpc_config
  keys:
    external: true
    name: drpc_keys

networks:
  drpc-proxy:
    name: drpc-proxy
  reverse-proxy:
    external: true
    name: reverse-proxy
  
services:
  dshackle:
    image: drpcorg/dshackle:${DSHACKLE_TAG:-latest}
    container_name: drpc-proxy
    volumes:
      # - ./config/config.yaml:/etc/dshackle/dshackle.yaml
      - ${DATABASE_CONFIG:-config}:/etc/dshackle
      - certs:/etc/dshackle/certs
      - ${DATABASE_KEYS:-keys}:/etc/dshackle/keys
    env_file:
      - .env.user
    expose:
      - 12448
    networks:
      - drpc-proxy
      - reverse-proxy
    environment:
      VIRTUAL_HOST: drpc.${PROVIDER_HOST}
      VIRTUAL_PORT: 12448
      LETSENCRYPT_HOST: drpc.${PROVIDER_HOST}
