volumes:
  certs:
    external: true
    name: reverse-proxy_certs

networks:
  drpc-proxy:
    name: drpc-proxy
  reverse-proxy:
    external: true
    name: reverse-proxy
  
services:
  dshackle:
    image: drpcorg/dshackle:${DSHACKLE_TAG:-latest}
    container_name: drpc-proxy
    volumes:
      - ${CONFIG_PATH:-./}/${PROVIDER}-dshackle.yaml:/etc/dshackle/dshackle.yaml
      - certs:/etc/dshackle/certs
      - ${KEYS_PATH:-./keys}:/etc/dshackle/keys
    env_file:
      - .env.user
    expose:
      - 12448
    networks:
      - drpc-proxy
      - reverse-proxy
    environment:
      VIRTUAL_HOST: drpc.${HOST}
      VIRTUAL_PORT: 12448
      LETSENCRYPT_HOST: drpc.${HOST}
