volumes:
  certs:
    external: true
    name: reverse-proxy_certs

networks:
  drpc-proxy:
    name: drpc-proxy
  reverse-proxy:
    external: true
    name: reverse-proxy
  
services:
  dshackle:
    image: drpcorg/dshackle:latest
    container_name: drpc-proxy
    volumes:
      - ./config/config.yaml:/etc/dshackle/dshackle.yaml
      - certs:/etc/dshackle/certs
      - ./keys:/etc/dshackle/keys
    expose:
      - 12448
    networks:
      - drpc-proxy
      - reverse-proxy
    environment:
      VIRTUAL_HOST: drpc.${PROVIDER_HOST}
      VIRTUAL_PORT: 12448
      LETSENCRYPT_HOST: drpc.${PROVIDER_HOST}