volumes:
  certs:
    external: true
    name: reverse-proxy_certs
  
services:
  dshackle:
    container_name: dshackle
    image: drpcorg/dshackle:latest
    volumes:
      - ./config/config.yaml:/etc/dshackle/dshackle.yaml
      - certs:/etc/dshackle/certs
      - ./keys:/etc/dshackle/keys
    ports:
      - "12448:12448"
    environment:
      VIRTUAL_HOST: drpc.${HOST}
      VIRTUAL_PORT: 12448
      LETSENCRYPT_HOST: drpc.${HOST}