erigon-archive:
  - id: ${ID}
    labels:
      provider: ${PROVIDER}
      archive: true
    connection:
      generic:
        rpc:
          url: ${RPC}
        ws:
          frameSize: 20Mb
          msgSize: 50Mb
          url: ${WS}
    chain: polygon
    method-groups:
      enabled:
        - debug
        - filter
        - trace
    methods:
      disabled:
      enabled:
        - name: txpool_content # TODO: should be disabled for rollup nodes
        # standard geth and erigon
        - name: debug_accountRange
        - name: debug_getModifiedAccountsByNumber
        - name: debug_getModifiedAccountsByHash
        # non standard geth and erigon
        - name: eth_getRawTransactionByHash
        - name: eth_getRawTransactionByBlockHashAndIndex
        # non standard erigon only
        - name: eth_getBlockReceipts
        - name: eth_protocolVersion
        - name: eth_callMany
        - name: eth_callBundle
        - name: debug_accountAt
        - name: debug_traceCallMany
        - name: erigon_getHeaderByHash
        - name: erigon_getBlockReceiptsByBlockHash
        - name: erigon_getHeaderByNumber
        - name: erigon_getLogsByHash
        - name: erigon_forks
        - name: erigon_getBlockByTimestamp
        - name: erigon_BlockNumber
        - name: erigon_getLatestLogs
        - name: ots_getInternalOperations
        - name: ots_hasCode
        - name: ots_getTransactionError
        - name: ots_traceTransaction
        - name: ots_getBlockDetails
        - name: ots_getBlockDetailsByHash
        - name: ots_getBlockTransactions
        - name: ots_searchTransactionsBefore
        - name: ots_searchTransactionsAfter
        - name: ots_getTransactionBySenderAndNonce
        - name: ots_getContractCreator
